kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-2
  template:
    metadata:
      labels:
        app: hello-world-2
    spec:
      containers:
        - name: hello-world-2
          image: localhost:32000/hello-world-2
          imagePullPolicy: Always